-- V1: esquema inicial de Office Platform.
--
-- Extraido con pg_dump de la base que Hibernate construyo con ddl-auto=update, y NO escrito a
-- mano. Con ddl-auto=validate cualquier diferencia entre este archivo y las entidades impide que
-- la aplicacion arranque, asi que el unico origen confiable es el esquema que ya esta en
-- produccion.
--
-- Sobre una base existente este archivo no se ejecuta: baseline-on-migrate la marca en la version
-- 1 y Flyway sigue desde V2. Se ejecuta solo en instalaciones nuevas, donde reproduce el mismo
-- punto de partida.

\restrict B54aMMvtRzEPyOuIbLuxq6dux8q2L6yg8QUJ03cXqF4Dnc6twaQrE0bSoeSWmW4


SET statement_timeout = 0;

CREATE TABLE public.activity_log (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    api_key_id bigint,
    details text,
    file_id bigint,
    file_name character varying(255),
    ip_address character varying(255),
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_id character varying(255),
    user_name character varying(255),
    folder_id bigint,
    CONSTRAINT activity_log_action_check CHECK (((action)::text = ANY (ARRAY['UPLOAD'::text, 'DOWNLOAD'::text, 'DELETE'::text, 'RESTORE'::text, 'PURGE'::text, 'RENAME'::text, 'EDITOR_OPEN'::text, 'EDITOR_SAVE'::text, 'CREATE_BLANK'::text, 'CREATE_FOLDER'::text, 'RENAME_FOLDER'::text, 'DELETE_FOLDER'::text, 'MOVE_FILE'::text, 'MOVE_FOLDER'::text, 'DOWNLOAD_FOLDER'::text, 'SHARE'::text, 'UNSHARE'::text, 'REVOKE_SHARE'::text, 'SESSION_TIMEOUT'::text])))
);

ALTER TABLE public.activity_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.admin_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_keys (
    id bigint NOT NULL,
    active boolean NOT NULL,
    api_key character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.editor_sessions (
    id bigint NOT NULL,
    api_key_id bigint NOT NULL,
    closed_at timestamp(6) without time zone,
    document_key character varying(255) NOT NULL,
    file_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    opened_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255),
    user_name character varying(255),
    last_heartbeat_at timestamp(6) without time zone
);

ALTER TABLE public.editor_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.editor_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.files (
    id bigint NOT NULL,
    api_key_id bigint NOT NULL,
    bucket character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    extension character varying(255),
    file_name character varying(255) NOT NULL,
    mime_type character varying(255) NOT NULL,
    object_name character varying(255) NOT NULL,
    original_file_name character varying(255) NOT NULL,
    size bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    folder_id bigint,
    user_id character varying(255),
    created_by_name character varying(255),
    updated_by_name character varying(255),
    created_by_user_id character varying(255)
);

ALTER TABLE public.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.folders (
    id bigint NOT NULL,
    api_key_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    parent_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid character varying(255) NOT NULL,
    user_id character varying(255),
    created_by_name character varying(255),
    updated_by_name character varying(255),
    created_by_user_id character varying(255)
);

ALTER TABLE public.folders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.folders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.known_users (
    id bigint NOT NULL,
    api_key_id bigint NOT NULL,
    display_name character varying(255),
    first_seen_at timestamp(6) without time zone NOT NULL,
    last_seen_at timestamp(6) without time zone NOT NULL,
    role character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE public.known_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.known_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    actor_name character varying(255),
    actor_user_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(500) NOT NULL,
    read_flag boolean NOT NULL,
    recipient_user_id character varying(255) NOT NULL,
    resource_id bigint,
    resource_type character varying(255),
    title character varying(255) NOT NULL
);

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portal_users (
    id bigint NOT NULL,
    cedula character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(255),
    last_login_at timestamp(6) without time zone,
    must_change_password boolean NOT NULL,
    password_hash character varying(255) NOT NULL
);

ALTER TABLE public.portal_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.share_permissions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    permission_level character varying(255) NOT NULL,
    resource_id bigint NOT NULL,
    resource_type character varying(255) NOT NULL,
    shared_by_name character varying(255),
    shared_by_user_id character varying(255),
    source_api_key_id bigint NOT NULL,
    target_api_key_id bigint,
    target_type character varying(255) NOT NULL,
    target_user_id character varying(255),
    notes text,
    CONSTRAINT share_permissions_permission_level_check CHECK (((permission_level)::text = ANY ((ARRAY['VIEW'::character varying, 'DOWNLOAD'::character varying, 'EDIT'::character varying])::text[]))),
    CONSTRAINT share_permissions_resource_type_check CHECK (((resource_type)::text = ANY ((ARRAY['FILE'::character varying, 'FOLDER'::character varying])::text[]))),
    CONSTRAINT share_permissions_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['USER'::character varying, 'PROJECT'::character varying])::text[])))
);

ALTER TABLE public.share_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.share_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.editor_sessions
    ADD CONSTRAINT editor_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT folders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT idx_admin_user_username UNIQUE (username);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT idx_api_key UNIQUE (api_key);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT idx_file_uuid UNIQUE (uuid);

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT idx_folder_uuid UNIQUE (uuid);

ALTER TABLE ONLY public.known_users
    ADD CONSTRAINT idx_known_user_api_key_user UNIQUE (api_key_id, user_id);

ALTER TABLE ONLY public.portal_users
    ADD CONSTRAINT idx_portal_user_cedula UNIQUE (cedula);

ALTER TABLE ONLY public.known_users
    ADD CONSTRAINT known_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portal_users
    ADD CONSTRAINT portal_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.share_permissions
    ADD CONSTRAINT share_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.known_users
    ADD CONSTRAINT uk_known_user_api_key_user UNIQUE (api_key_id, user_id);

ALTER TABLE ONLY public.portal_users
    ADD CONSTRAINT uk_portal_user_cedula UNIQUE (cedula);

CREATE INDEX idx_activity_log_action ON public.activity_log USING btree (action);

CREATE INDEX idx_activity_log_api_key_id ON public.activity_log USING btree (api_key_id);

CREATE INDEX idx_activity_log_timestamp ON public.activity_log USING btree ("timestamp");

CREATE INDEX idx_api_key_active ON public.api_keys USING btree (active);

CREATE INDEX idx_editor_session_api_key_id ON public.editor_sessions USING btree (api_key_id);

CREATE INDEX idx_editor_session_closed_at ON public.editor_sessions USING btree (closed_at);

CREATE INDEX idx_editor_session_document_key ON public.editor_sessions USING btree (document_key);

CREATE INDEX idx_editor_session_file_id ON public.editor_sessions USING btree (file_id);

CREATE INDEX idx_file_api_key_id ON public.files USING btree (api_key_id);

CREATE INDEX idx_file_created_at ON public.files USING btree (created_at);

CREATE INDEX idx_file_folder_id ON public.files USING btree (folder_id);

CREATE INDEX idx_file_user_id ON public.files USING btree (user_id);

CREATE INDEX idx_folder_api_key_id ON public.folders USING btree (api_key_id);

CREATE INDEX idx_folder_parent_id ON public.folders USING btree (parent_id);

CREATE INDEX idx_folder_user_id ON public.folders USING btree (user_id);

CREATE INDEX idx_known_user_api_key_id ON public.known_users USING btree (api_key_id);

CREATE INDEX idx_notification_recipient ON public.notifications USING btree (recipient_user_id);

CREATE INDEX idx_notification_recipient_read ON public.notifications USING btree (recipient_user_id, read_flag);

CREATE INDEX idx_share_resource ON public.share_permissions USING btree (resource_type, resource_id);

CREATE INDEX idx_share_source_api_key ON public.share_permissions USING btree (source_api_key_id);

CREATE INDEX idx_share_target_api_key ON public.share_permissions USING btree (target_api_key_id);

CREATE INDEX idx_share_target_user ON public.share_permissions USING btree (target_user_id);

\unrestrict B54aMMvtRzEPyOuIbLuxq6dux8q2L6yg8QUJ03cXqF4Dnc6twaQrE0bSoeSWmW4;
