-- V3: historial de versiones de archivos.
--
-- Guardar desde el editor sobrescribia el objeto en el almacenamiento y el contenido previo se
-- perdia sin rastro. Cada fila apunta a una copia completa del binario anterior, no a un diff:
-- los formatos ofimaticos son ZIP comprimidos y un diff binario sobre ellos no es ni pequeno ni
-- interpretable.
--
-- La fila guarda el estado PREVIO al guardado, no el nuevo. El contenido vigente sigue en
-- files.object_name, asi que la descarga y el editor no cambian, y restaurar una version es
-- copiar su objeto sobre el actual.

CREATE TABLE IF NOT EXISTS file_versions (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id            bigint NOT NULL,
    version_number     integer NOT NULL,
    object_name        character varying(255) NOT NULL,
    size               bigint,
    created_by_user_id character varying(255),
    created_by_name    character varying(255),
    created_at         timestamp(6) without time zone NOT NULL,
    comment            character varying(255)
);

-- Sin clave foranea hacia files, en linea con el resto del esquema, que tampoco las usa. Purgar
-- un archivo borra sus versiones explicitamente en FileVersionService, junto con sus binarios:
-- una cascada de base de datos dejaria los objetos huerfanos en el almacenamiento.

-- El correlativo es por archivo. La restriccion evita que dos guardados simultaneos escriban la
-- misma version y que el historial quede con numeros repetidos.
ALTER TABLE file_versions
    ADD CONSTRAINT uk_file_version_number UNIQUE (file_id, version_number);

CREATE INDEX IF NOT EXISTS idx_file_version_file_id ON file_versions (file_id);
CREATE INDEX IF NOT EXISTS idx_file_version_created_at ON file_versions (created_at);
